### ISSUE TITLE
Infinite attachments?

### ISSUE THREAD

**Issue by chrisamirani** [resendlabs/resend-node#101]
Hi @bukinoshita 
Was wondering how are these set to `Infinity` and if the API actually supports that. https://github.com/resendlabs/resend-node/blob/f52cc34c73f328af71829f6c8dfa64ebf8fc6776/src/resend.ts#L39-L40 

Thanks and keep up the great work you guys!

**Comment by bukinoshita** [comment]
This is actually only for the SDK, we have limits in the API for attachments
