### ISSUE TITLE
How to encode diacritics

### ISSUE THREAD

**Issue by andrecasal** [resendlabs/resend-node#110]
In this example
```tsx
import { json } from '@remix-run/node'
import { Resend } from 'resend'

const resend = new Resend(process.env.MAIL_SERVICE_API_KEY)

export const loader = async () => {
	try {
		const data = await resend.emails.send({
			from: 'André Casal <hello@transactional.mydomain.com>',
			to: 'someone@gmail.com',
			subject: 'Hello world',
			html: '<strong>It works!</strong>',
		})

		return json(data, 200)
	} catch (error) {
		return json({ error }, 400)
	}
}
```

The email is sent with an invalid character:
<img width="775" alt="Screenshot 2023-06-15 at 21 14 33" src="https://github.com/resendlabs/resend-node/assets/22457463/37e1c771-6608-44dc-bba7-504ba29a7a6e">

How would one send diacritics correctly?

**Comment by bukinoshita** [comment]
What email client are you using?

**Comment by myarete** [comment]
> What email client are you using?

@bukinoshita Protonmail

**Comment by bukinoshita** [comment]
> > What email client are you using?
> 
> @bukinoshita Protonmail

Would mind sharing your request body?

**Comment by bukinoshita** [comment]
This should be fixed.
