### ISSUE TITLE
Problem with next.js

### ISSUE THREAD

**Issue by OverVlad** [resendlabs/resend-node#141]
Hello,

I faced with problem when tried to integrate in next.js application.

## Package versions
Problem with 12 and 13 version of next.js

```
    "next": "^13.4.10",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "typescript": "4.5.5"
```

## How to reproduce
- Add resend nom package `yarn add resend`
- run `yarn build` or `next build`

## Result
```
./node_modules/type-fest/source/camel-case.d.ts:25:32
Type error: '?' expected.
```
<img width="676" alt="image" src="https://github.com/resendlabs/resend-node/assets/15329933/dc55191a-b4f1-4d45-8cec-a1a7db2758dc">

**Comment by OverVlad** [comment]
As I understood problem because of dependencies [here](https://github.com/resendlabs/resend-node/blob/4d8f63c4690cdfec9d7825722d7b9a28eae1531f/package.json#L32C6-L32C15)

**Comment by OverVlad** [comment]
After updating to the newest typescript version ("typescript": "^5.1.6") problem was solved. I can suggest to add typescript version requirement

**Comment by bukinoshita** [comment]
The issue was with the Typescript version?

**Comment by OverVlad** [comment]
@bukinoshita Yes. I fixed this by upgrading my typescript version
