### ISSUE TITLE
Getting ECONNREFUSED sending email

### ISSUE THREAD

**Issue by husamrahman** [resendlabs/resend-node#147]
I feel like I'm missing something. This issue only recently started popping up. I keep getting an ECONNREFUSED error simply trying to send an email out. Not sure why its pointing to 127.0.0.1:3001. Any help would be great thank you!

Below is the call I'm making

`
  await resend.emails.send({
    from: 'some@email',
    to: email,
    subject: `Free Trial Activated  🙌`,
    html,
  }).catch((err) => logger.error(err));
};
`

`"message":"connect ECONNREFUSED 127.0.0.1:3001","name":"Error","stack":"Error: connect ECONNREFUSED 127.0.0.1:3001\n    at Function.AxiosError.from (..../node_modules/resend/node_modules/axios/lib/core/AxiosError.js:89:14)\n    at RedirectableRequest.handleRequestError (.../node_modules/resend/node_modules/axios/lib/adapters/http.js:591:25)\n    at RedirectableRequest.emit (node:events:390:28)\n    at ClientRequest.eventHandlers.<computed> (.../node_modules/follow-redirects/index.js:14:24)\n    at ClientRequest.emit (node:events:390:28)\n    at Socket.socketErrorListener (node:_http_client:447:9)\n    at Socket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","code":"ECONNREFUSED"},"msg":"connect ECONNREFUSED 127.0.0.1:3001"}`

**Comment by Kartik4152** [comment]
Same

**Comment by zenorocha** [comment]
Are you using the latest version `0.17.2`?

**Comment by husamrahman** [comment]
That was it. I had to force it to upgrade to latest. Thank you for the quick help 🙏

**Comment by hmmhmmhm** [comment]
<img width="330" alt="스크린샷 2023-12-08 오전 9 51 36" src="https://github.com/resendlabs/resend-node/assets/38493722/48df16a8-02e0-4224-b7ea-d8d4276a6c72">

I hadn't updated the email module in a while and just realized I was getting an error in July.
What was this error? I hadn't changed anything in the legacy project.
