### ISSUE TITLE
Error is not in return type

### ISSUE THREAD

**Issue by probablykasper** [resendlabs/resend-node#188]
Error responses are returned (not thrown) the same way as a normal response, as you can see here:
https://github.com/resendlabs/resend-node/blob/e9a11863d4ba37d6245c9ac9ee328337a138f3ca/src/resend.ts#L42-L47

But the type says it returns a `CreateEmailResponse`, which is not an error type:
https://github.com/resendlabs/resend-node/blob/e9a11863d4ba37d6245c9ac9ee328337a138f3ca/src/emails/emails.ts#L14-L17
https://github.com/resendlabs/resend-node/blob/e9a11863d4ba37d6245c9ac9ee328337a138f3ca/src/emails/interfaces/create-email-options.interface.ts#L87-L89

**Comment by matt-aitken** [comment]
I'm having the same problem, I think best practice here is to throw an error.

Failing that it should be easier to discriminate between a success and error by using a discriminated union:

```ts

type CreateEmailResponse = {
  success: true;
  id: string;
}

type ErrorResponse = {
  success: false;
  …
}

```

**Comment by probablykasper** [comment]
Throwing errors means you don't get any type safety, which is really bad (and it makes it easy to not handle errors). Returning a type like this would be great:
```type
{
  id: string
  error?: undefined
} | {
  error: {
    ...
  }
}
```

**Comment by jayanratna** [comment]
I am currently exploring ways to resolve this issue...

Would it make sense to have a custom `ResendError` class that is thrown (instead of returning the error response, like it currently is)? Could potentially add `message`, `name` and `statusCode` methods to retrieve those additional values if the `message` itself isn't enough.

**Comment by vcapretz** [comment]
see https://github.com/resendlabs/resend-node/issues/150#issuecomment-1722526403

I agree with @probablykasper that throwing would not be the best approach, we are polishing how we do the return type so consumers can correctly narrow the response 🙏
