### ISSUE TITLE
[bug] ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by CracKerMe** [resendlabs/resend-node#233]
if you meet this bug,Don't warry about it.

this bug caused by a new programer feature "[new Headers()](https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers)",

that means you can upgrade your node version to higher.

i meet this bug on **Node v16.19.0**. when i solve this bug on **Node v18.17.1**

**Comment by CracKerMe** [comment]
By the way,
If possible, please update the minimum node dependency version number of this npm package, that would be great

**Comment by CracKerMe** [comment]
[https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers#browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers#browser_compatibility)

Headers is supported from Node v18.0.0 (Released 2022-04-19)

**Comment by sgrund14** [comment]
is there a way to avoid this issue using node 16? still want the ability to add an unsubscribe link

**Comment by zenorocha** [comment]
Unfortunately, Node.js 16 has reached End-of-Life [1] and only Node 18 is supported by this package [2].

[1] https://nodejs.org/en/blog/announcements/nodejs16-eol
[2] https://github.com/resendlabs/resend-node/blob/main/package.json#L10-L12
