### ISSUE TITLE
Headers is not defined

### ISSUE THREAD

**Issue by AngelKrak** [resendlabs/resend-node#236]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `resend@1.1.0` for the project I'm working on.

Fix error "headers is not defined".

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/resend/build/src/resend.js b/node_modules/resend/build/src/resend.js
index 297f53b..a6bd654 100644
--- a/node_modules/resend/build/src/resend.js
+++ b/node_modules/resend/build/src/resend.js
@@ -10,6 +10,8 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, ge
 };
 Object.defineProperty(exports, "__esModule", { value: true });
 exports.Resend = void 0;
+const fetch = require('node-fetch');
+const { Headers } = fetch;
 const render_1 = require("@react-email/render");
 const package_json_1 = require("../package.json");
 const api_keys_1 = require("./api-keys/api-keys");
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by zenorocha** [comment]
Unfortunately, Node.js 16 has reached End-of-Life [1], and only Node 18 is supported by this package [2].

[1] https://nodejs.org/en/blog/announcements/nodejs16-eol
[2] https://github.com/resendlabs/resend-node/blob/main/package.json#L10-L12
