### ISSUE TITLE
Uprading from `1.1.0` to `2.0.0` causes Next.js app to fail at build: `Failed to compile.  ./node_modules/.pnpm/html-to-text@9.0.5/node_modules/html-to-text/lib/html-to-text.mjs + 24 modules Cannot get final name for export 'encodeXML' of ./node_modules/.pnpm/entities@4.5.0/node_modules/entities/lib/esm/index.js`

### ISSUE THREAD

**Issue by pjborowiecki** [resendlabs/resend-node#257]
I have tried updating the `resend` package from version `1.1.0` to the lates, but it caused my Next.js 14 app to fail at build with the following error:

`Failed to compile.  ./node_modules/.pnpm/html-to-text@9.0.5/node_modules/html-to-text/lib/html-to-text.mjs + 24 modules Cannot get final name for export 'encodeXML' of ./node_modules/.pnpm/entities@4.5.0/node_modules/entities/lib/esm/index.js`

I tried all the canary versions and the latest release (`2.0.0`), but the issue appears in all of them. 

The moment I remove the package entirely or revert back to 1.1.0`, the app builds fine again.

**Comment by edwardribas** [comment]
Same problem here.

**Comment by bukinoshita** [comment]
Can you share a snippet code on how are you using it?

**Comment by bukinoshita** [comment]
This is duplicated of https://github.com/resendlabs/resend-node/issues/256. Can you follow up there?

**Comment by Vijayaraj-Anbalagan** [comment]
easy way is to uninstall the package and re install the ``version 0.16.0``
