### ISSUE TITLE
Footer in lading page overflowing

### ISSUE THREAD

**Issue by davidfcopozo** [resendlabs/resend-node#39]
## Issue:
As can be seen in the picture set out below, the footer is overflowing and there is no padding in or space above the header.
![image](https://user-images.githubusercontent.com/46207472/210835042-a3cf6401-16a6-457e-ae1e-3855e3450adf.png)

## Replicate issue:
The overflow can be seen in a 1366px inner width by 625px inner height screen.

## Possible solution:
Decrease Rubrik Cube's size in the given breakpoint and make sure there is padding in the header

**Comment by bukinoshita** [comment]
This was fixed.
