### ISSUE TITLE
example of how to mock resend nodejs sdk

### ISSUE THREAD

**Issue by daniloab** [resendlabs/resend-node#44]
Hi, im implementing resend in a nodejs server and it would be cool to have exampels of how to mock the sdk with jest tests

**Comment by leonardobrito** [comment]
Hi @daniloab, hope this example works for you:

```js
const { sendEmail } = require("./sendEmail");
const { Resend } = require('resend');

describe('Resend sendEmail', () => {
  let spySendEmail
  beforeEach(() => {
    spySendEmail = jest.spyOn(Resend.prototype, 'sendEmail').mockImplementation(() => { });
    sendEmail()
  })

  it('it should call sendEmail from resend', () => {
    expect(spySendEmail).toHaveBeenCalledTimes(1);
    expect(spySendEmail).toHaveBeenCalledWith({
      "from": "you@example.com",
      "subject": "hello world",
      "text": "it works!",
      "to": "user@gmail.com",
    })
  })
})
```

I've created this [small project](https://github.com/leonardobrito/resend-node-mock) for it.

**Comment by bukinoshita** [comment]
Thanks @leonardobrito!

Were you able to mock your tests @daniloab ?

**Comment by daniloab** [comment]
> Thanks @leonardobrito!
> 
> Were you able to mock your tests @daniloab ?

I will give it a try until the weekend and I will let you know

**Comment by daniloab** [comment]
Im testing here and looks like the `toHaveBeenCalledWith` function is not working well on the backend. 

My test is on the backend, Im using GraphQL, then, after a mutation I trigger the resend email with my email props. Since the props passed has a react component and my expect files don't, it is breaking. I would like to remove the react component from the check.

But, looks like spy on is working!

**Comment by daniloab** [comment]
I replaced the `toHaveBeenCalledWith` to `toEqual` getting the mock object:
```ts
  const spySendEmailCall = spySendEmail.mock.calls[0][0];

  const { react, ...restSpySendEmailCall} = spySendEmailCall;

  expect(restSpySendEmailCall).toEqual({
    from: 'marketing.com.br,
    subject: 'Welcome',
    to: 'email@test.com',
  });
```

now, Im wondering how to match the react component with expected the values since the test in on backend.
