### ISSUE TITLE
[Suggestion] lightweight client without react email / axios

### ISSUE THREAD

**Issue by 0xAsimetriq** [resendlabs/resend-node#46]
Hey guys,

Been loving experience around resend's sdk thus far and decided to swing by and leave a suggestion. After glancing at internals it seems like you could offer a more lightweight (additional?) client via dropping `@react-email/render` and `axios` and utalising node's native fetch client.

Such client could come handy for newer projects / not using react perhaps?

**Comment by samkingco** [comment]
Commenting on this closed issue, so apologies, but I second this. Would be great to be able to send emails from Vercel's edge runtime. Right now it errors due to the dependencies on axios.
