### ISSUE TITLE
[suggestion] resend domain docs with example

### ISSUE THREAD

**Issue by daniloab** [resendlabs/resend-node#51]
Hi, there. 

I dont know if resend docs are open sourced, so I will let a suggestion here.

## Context
After implementing a domain to send my emails I was passing the domain only. For example, lets assume the domain from original docs `updates.example.com`.

Inside my implementation I was passing

```ts
await resend.sendEmail({
      from: 'updates.example.com',
      to: 'hi@daniloassis.dev',
      subject: 'Welcome!',
      html:
        '<div>\n' +
        '      <h1>Welcome!</h1>\n' +
        '      <p>Hello, Danilo</p>\n' +
        '    </div>',
    });
```

and receiving errors like `Identity not found`.

## Problem
So, trying to figure out how to fix I remember from examples that in the `from` prop is passed a plain email:
```ts
from: 'onboarding@resend.dev',
```
Then, I tested pass an email with my domain
```ts
await resend.sendEmail({
      from: 'notanswer@updates.example.com',
      to: 'hi@daniloassis.dev',
      subject: 'Welcome!',
      html:
        '<div>\n' +
        '      <h1>Welcome!</h1>\n' +
        '      <p>Hello, Danilo</p>\n' +
        '    </div>',
    });
```
and it works!

## Doc
My suggestion is a doc explaning this step to be clear how to use. 

> Resend is my first interation configuring an own Email integration for my platform, so Im learning everything from zero. Then, having a documentation for this step could be helpful.

Docs:
```markdown
## How to use your domain to send emails
After configuring your domain inside Resend have sure to have it with status `verified`. This mean the domain is working.
```
```ts
await resend.sendEmail({
      from: 'notanswer@updates.example.com',
      to: 'hi@daniloassis.dev',
      subject: 'Welcome!',
      html:
        '<div>\n' +
        '      <h1>Welcome!</h1>\n' +
        '      <p>Hello, Danilo</p>\n' +
        '    </div>',
    });
```

```markdown
Then, in your implementation choose your a word to to complement your email and send it:
```
Let me know if Im mismatching some knowledge here and if this make sense!

Thanks @zenorocha and @bukinoshita

**Comment by bukinoshita** [comment]
We added some error handling, so the error is displayed in the error message as

![CleanShot 2023-03-15 at 02 55 49@2x](https://user-images.githubusercontent.com/6929565/225461618-65edbf40-9cf4-4559-9d83-e99315f76e7a.png)
