### ISSUE TITLE
question about environments

### ISSUE THREAD

**Issue by colinricardo** [resendlabs/resend-node#71]
what is the best way to avoid sending emails in non-production environments?

is it to add a MockResend class or is there a param I can pass to the constructor?

**Comment by bukinoshita** [comment]
Do you want to send actual emails to inbox or just sending to for example `success@resend.dev` and returning a success event would work?

**Comment by colinricardo** [comment]
just a fake success response, something like this: 

```
class MockResend extends Resend {
  sendEmail = async (data: SendEmailData): Promise<SendEmailResponse> => {
    const { react, ...rest } = data;
    const { props } = react;
    log("Would have sent email in production", { ...rest, props });
    return {
      id: "xxx",
      created_at: "xxx",
    } as SendEmailResponse;
  };
}
```

**Comment by bukinoshita** [comment]
It's not yet documented, but we worked on sending emails with our testing emails. So try sending an email to and let me know

- `success@resend.dev`
- `bounces@resend.dev`
