### ISSUE TITLE
How to test Mock Emails in cypress using Integration tests

### ISSUE THREAD

**Issue by fxmb** [resendlabs/resend-node#94]
I have a test that e.g. tests a user signup. We send a welcome email at the end. What is the best way to test this and send (and receive?) a mock email and validate it? I am quite new to programming emails in general so any pointers to the docs (couldnt find) or useful repos are highly appreciated 🙏.

**Comment by fxmb** [comment]
We are using resend and react email. I would like to test this on an express server if possible

**Comment by fxmb** [comment]
Does anyone have an idea here how to set up email testing?

**Comment by bukinoshita** [comment]
> Does anyone have an idea here how to set up email testing?

Hey, there're a few things you can do. If you don't want to send emails, you can mock Resend sendEmail function, with a mocked response. If you want to to actual send test emails, you can add one of our testing email address on "to" ([Docs
](https://resend.com/docs/dashboard/emails/send-test-emails)).

If you want this to be in your CI, I'd recommend just mocking Resend package and function.

**Comment by fxmb** [comment]
Thanks for that answer and pointer. When I sent an email I get a DNS error. Is this intended?

```
Address not found
Your message wasn't delivered to delivered@resend.dev because the domain resend.dev couldn't be found. Check for typos or unnecessary spaces and try again.
```

And in case it is delivered, how would I check it has actually arrived the way I intended?

Thanks for your help @bukinoshita

**Comment by bukinoshita** [comment]
> Thanks for that answer and pointer. When I sent an email I get a DNS error. Is this intended?
> 
> ```
> Address not found
> Your message wasn't delivered to delivered@resend.dev because the domain resend.dev couldn't be found. Check for typos or unnecessary spaces and try again.
> ```
> 
> And in case it is delivered, how would I check it has actually arrived the way I intended?
> 
> Thanks for your help @bukinoshita

Would mind sharing your code? It will be easier to debug where the error is.
