### ISSUE TITLE
send bulk emails

### ISSUE THREAD

**Issue by LucasAlda** [resendlabs/resend-node#99]
Hi, I really love the react-email and resend ecosystem and I want to migrate but in most of my projects I find myself using bulk emails to send email to long lists without having issues with the rate limit while being on a serverless runtime without an "easy" way to have a queue implemented. Are you planning on adding this feature in the near future?

**Comment by bukinoshita** [comment]
Hey @LucasAlda. Yes, sending in Bulk is on the roadmap. It's something that we want to release soon.

**Comment by colburncodes** [comment]
Is there any update on this? @bukinoshita
